name: brepnet
channels:
  - conda-forge
  - defaults
  - lambouj
dependencies:
  - python=3.7
  - pythonocc-core=7.5.1
  - pytorch
  - tqdm
  - igl
  - scikit-learn
  - pytorch-lightning
  - xlsxwriter
  - occwl
  - jupyter
  - pythreejs


