name: brepnet
channels:
  - conda-forge
  - defaults
  - lambouj
dependencies:
  - python=3.7
  - pythonocc-core=7.5.1
  - pytorch=1.7.1
  - tqdm=4.64.0
  - igl=2.2.1
  - scikit-learn=1.0.2
  - pytorch-lightning=1.5.10
  - xlsxwriter=3.0.3
  - occwl=1.0.0
  - jupyter=1.0.0
  - pythreejs=2.3.0
  - tensorboard=2.9.0

