name: brepnet
channels:
  - conda-forge
  - defaults
  - lambouj
  - dglteam
dependencies:
  - python=3.7
  - pythonocc-core=7.5.1
  - pytorch
  - dgl-cuda11.1-0.7.0-py37_0
  - tqdm
  - igl
  - scikit-learn
  - pytorch-lightning
  - xlsxwriter
  - occwl
  - jupyter
  - pythreejs
  - tensorboard

